apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-dev-serve-api-pv
spec:
  capacity:
    storage: 100Gi  # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  local:
    path: /var/lib/k8s-storage/dev-workspace/wwwroot
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube     

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-dev-serve-api-pvc
  namespace: dev-workspace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi  # Adjust to match the size specified in the PV

