apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: dev-workspace
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiI0ZWRlcGxveSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfQ0w1UkFFZ0lHdm93LURUdXFrbXdNMHBsMmVzIiwiYXV0aCI6Ik5HVmtaWEJzYjNrNlpHTnJjbDl3WVhSZlEwdzFVa0ZGWjBsSGRtOTNMVVJVZFhGcmJYZE5NSEJzTW1WeiJ9fX0=